/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#6a37d4",
        "error-container": "#fb5151",
        "on-primary-container": "#00214f",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#6c9fff",
        "on-primary-fixed": "#000000",
        "background": "#f5f7f9",
        "primary": "#0058bb",
        "surface-container-highest": "#d9dde0",
        "on-surface": "#2c2f31",
        "error": "#b31b25",
        "on-tertiary-container": "#004b58",
        "on-primary": "#f0f2ff",
        "tertiary-fixed-dim": "#40ceed",
        "surface-dim": "#d0d5d8",
        "secondary-fixed-dim": "#ceb9ff",
        "primary-container": "#6c9fff",
        "outline-variant": "#abadaf",
        "surface-container-high": "#dfe3e6",
        "surface": "#f5f7f9",
        "inverse-on-surface": "#9a9d9f",
        "error-dim": "#9f0519",
        "outline": "#747779",
        "secondary-container": "#dac9ff",
        "on-tertiary-fixed": "#003640",
        "on-secondary": "#f8f0ff",
        "tertiary-fixed": "#53ddfc",
        "tertiary-container": "#53ddfc",
        "on-secondary-fixed": "#40009b",
        "on-primary-fixed-variant": "#002a61",
        "tertiary-dim": "#005867",
        "tertiary": "#006576",
        "on-error-container": "#570008",
        "inverse-surface": "#0b0f10",
        "on-secondary-fixed-variant": "#5f28c8",
        "surface-variant": "#d9dde0",
        "on-error": "#ffefee",
        "on-tertiary-fixed-variant": "#005564",
        "on-background": "#2c2f31",
        "on-secondary-container": "#5517bf",
        "surface-container-low": "#eef1f3",
        "surface-bright": "#f5f7f9",
        "secondary-dim": "#5e26c7",
        "surface-tint": "#0058bb",
        "inverse-primary": "#4b8eff",
        "primary-fixed-dim": "#5191ff",
        "on-surface-variant": "#595c5e",
        "secondary-fixed": "#dac9ff",
        "primary-dim": "#004ca4",
        "on-tertiary": "#def7ff",
        "surface-container": "#e5e9eb"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"]
      }
    },
  },
  plugins: [],
}
